import 'package:project_quran/data/model/surah_model.dart';

List<SurahModel> allSurahList = [
  SurahModel(
    surahNo: 01,
    surahNameEn: 'Al Fatiha',
    surahNameAr: '001',
    nameTranslation: 'The Opening',
    nameOftranslation: 'English - Sahih International',
    revelationType: 'Maccan',
    ayah: 7,
    listOfAyat: [
      'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ',
      'ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'مَـٰلِكِ يَوْمِ ٱلدِّينِ',
      'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
      'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ ',
      'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
    ],
    listOfTranslation: [
      'In the Name of Allah—the Most Compassionate, Most Merciful.',
      'All praise is for Allah—Lord of all worlds,',
      'the Most Compassionate, Most Merciful,',
      'Master of the Day of Judgment.',
      'You ˹alone˺ we worship and You ˹alone˺ we ask for help.',
      'Guide us along the Straight Path,',
      'the Path of those You have blessed—not those You are displeased with, or those who are astray.',
    ],
  ),
  SurahModel(
    surahNo: 02,
    surahNameEn: 'Al Baqarah',
    surahNameAr: '002',
    nameTranslation: 'The Cow',
    nameOftranslation: 'English - Sahih International',
    revelationType: 'Madina',
    ayah: 286,
    listOfAyat: [
      'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ',
      'ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'مَـٰلِكِ يَوْمِ ٱلدِّينِ',
      'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
      'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ ',
      'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
    ],
    listOfTranslation: [
      'In the Name of Allah—the Most Compassionate, Most Merciful.',
      'All praise is for Allah—Lord of all worlds,',
      'the Most Compassionate, Most Merciful,',
      'Master of the Day of Judgment.',
      'You ˹alone˺ we worship and You ˹alone˺ we ask for help.',
      'Guide us along the Straight Path,',
      'the Path of those You have blessed—not those You are displeased with, or those who are astray.',
    ],
  ),
  SurahModel(
    surahNo: 03,
    surahNameEn: 'Ali’Imran',
    surahNameAr: '003',
    nameTranslation: 'Family Of Imran',
    nameOftranslation: 'English - Sahih International',
    revelationType: 'Madina',
    ayah: 200,
    listOfAyat: [
      'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ',
      'ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'مَـٰلِكِ يَوْمِ ٱلدِّينِ',
      'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
      'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ ',
      'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
    ],
    listOfTranslation: [
      'In the Name of Allah—the Most Compassionate, Most Merciful.',
      'All praise is for Allah—Lord of all worlds,',
      'the Most Compassionate, Most Merciful,',
      'Master of the Day of Judgment.',
      'You ˹alone˺ we worship and You ˹alone˺ we ask for help.',
      'Guide us along the Straight Path,',
      'the Path of those You have blessed—not those You are displeased with, or those who are astray.',
    ],
  ),
  SurahModel(
    surahNo: 04,
    surahNameEn: 'An Nisa',
    surahNameAr: '004',
    nameTranslation: 'The Women',
    nameOftranslation: 'English - Sahih International',
    revelationType: 'Madina',
    ayah: 176,
    listOfAyat: [
      'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ',
      'ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'مَـٰلِكِ يَوْمِ ٱلدِّينِ',
      'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
      'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ ',
      'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
    ],
    listOfTranslation: [
      'In the Name of Allah—the Most Compassionate, Most Merciful.',
      'All praise is for Allah—Lord of all worlds,',
      'the Most Compassionate, Most Merciful,',
      'Master of the Day of Judgment.',
      'You ˹alone˺ we worship and You ˹alone˺ we ask for help.',
      'Guide us along the Straight Path,',
      'the Path of those You have blessed—not those You are displeased with, or those who are astray.',
    ],
  ),
  SurahModel(
    surahNo: 05,
    surahNameEn: 'Al Ma’idah',
    surahNameAr: '005',
    nameTranslation: 'The Table Spread',
    nameOftranslation: 'English - Sahih International',
    revelationType: 'Madina',
    ayah: 120,
    listOfAyat: [
      'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ',
      'ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'مَـٰلِكِ يَوْمِ ٱلدِّينِ',
      'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
      'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ ',
      'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
    ],
    listOfTranslation: [
      'In the Name of Allah—the Most Compassionate, Most Merciful.',
      'All praise is for Allah—Lord of all worlds,',
      'the Most Compassionate, Most Merciful,',
      'Master of the Day of Judgment.',
      'You ˹alone˺ we worship and You ˹alone˺ we ask for help.',
      'Guide us along the Straight Path,',
      'the Path of those You have blessed—not those You are displeased with, or those who are astray.',
    ],
  ),
  SurahModel(
    surahNo: 05,
    surahNameEn: 'Al Ma’idah',
    surahNameAr: '005',
    nameTranslation: 'The Table Spread',
    nameOftranslation: 'English - Sahih International',
    revelationType: 'Madina',
    ayah: 120,
    listOfAyat: [
      'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ',
      'ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'مَـٰلِكِ يَوْمِ ٱلدِّينِ',
      'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
      'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ ',
      'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
    ],
    listOfTranslation: [
      'In the Name of Allah—the Most Compassionate, Most Merciful.',
      'All praise is for Allah—Lord of all worlds,',
      'the Most Compassionate, Most Merciful,',
      'Master of the Day of Judgment.',
      'You ˹alone˺ we worship and You ˹alone˺ we ask for help.',
      'Guide us along the Straight Path,',
      'the Path of those You have blessed—not those You are displeased with, or those who are astray.',
    ],
  ),
  SurahModel(
    surahNo: 5,
    surahNameEn: 'Al Ma’idah',
    surahNameAr: '005',
    nameTranslation: 'The Table Spread',
    nameOftranslation: 'English - Sahih International',
    revelationType: 'Madina',
    ayah: 120,
    listOfAyat: [
      'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ',
      'ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'مَـٰلِكِ يَوْمِ ٱلدِّينِ',
      'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
      'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ ',
      'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
    ],
    listOfTranslation: [
      'In the Name of Allah—the Most Compassionate, Most Merciful.',
      'All praise is for Allah—Lord of all worlds,',
      'the Most Compassionate, Most Merciful,',
      'Master of the Day of Judgment.',
      'You ˹alone˺ we worship and You ˹alone˺ we ask for help.',
      'Guide us along the Straight Path,',
      'the Path of those You have blessed—not those You are displeased with, or those who are astray.',
    ],
  ),
  SurahModel(
    surahNo: 5,
    surahNameEn: 'Al Ma’idah',
    surahNameAr: '005',
    nameTranslation: 'The Table Spread',
    revelationType: 'Madina',
    nameOftranslation: 'English - Sahih International',
    ayah: 120,
    listOfAyat: [
      'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ',
      'ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'مَـٰلِكِ يَوْمِ ٱلدِّينِ',
      'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
      'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ ',
      'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
    ],
    listOfTranslation: [
      'In the Name of Allah—the Most Compassionate, Most Merciful.',
      'All praise is for Allah—Lord of all worlds,',
      'the Most Compassionate, Most Merciful,',
      'Master of the Day of Judgment.',
      'You ˹alone˺ we worship and You ˹alone˺ we ask for help.',
      'Guide us along the Straight Path,',
      'the Path of those You have blessed—not those You are displeased with, or those who are astray.',
    ],
  ),
  SurahModel(
    surahNo: 5,
    surahNameEn: 'Al Ma’idah',
    surahNameAr: '005',
    nameTranslation: 'The Table Spread',
    nameOftranslation: 'English - Sahih International',
    revelationType: 'Madina',
    ayah: 120,
    listOfAyat: [
      'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ',
      'ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
      'مَـٰلِكِ يَوْمِ ٱلدِّينِ',
      'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
      'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ ',
      'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
    ],
    listOfTranslation: [
      'In the Name of Allah—the Most Compassionate, Most Merciful.',
      'All praise is for Allah—Lord of all worlds,',
      'the Most Compassionate, Most Merciful,',
      'Master of the Day of Judgment.',
      'You ˹alone˺ we worship and You ˹alone˺ we ask for help.',
      'Guide us along the Straight Path,',
      'the Path of those You have blessed—not those You are displeased with, or those who are astray.',
    ],
  ),
];

